/**
 * Cross-implementation gate (spec Sec. 4).
 *
 * Replays every fixture in tests/golden/rng.json -- generated by the Rust
 * `mathsim golden` -- through the TypeScript engine. Any single mismatch means
 * the server and the player's own verifier would disagree about what a spin
 * rolled, so this exits non-zero on the first failure.
 *
 *   node --experimental-strip-types tests/verify-golden.ts
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { HmacRng, serverSeedHash } from "../packages/engine/src/rng/index.ts";

interface GoldenCase {
  serverSeedHex: string;
  serverSeedHash: string;
  clientSeed: string;
  nonce: number;
  gameId: string;
  bounds: number[];
  values: number[];
}

const here = dirname(fileURLToPath(import.meta.url));
const goldenPath = join(here, "golden", "rng.json");
const golden = JSON.parse(readFileSync(goldenPath, "utf8")) as { cases: GoldenCase[] };

let checkedValues = 0;
const failures: string[] = [];

for (const [index, testCase] of golden.cases.entries()) {
  const serverSeed = Buffer.from(testCase.serverSeedHex, "hex");

  const hash = serverSeedHash(serverSeed);
  if (hash !== testCase.serverSeedHash) {
    failures.push(`case ${index}: SHA-256 commitment mismatch: ${hash} != ${testCase.serverSeedHash}`);
  }

  const rng = new HmacRng(serverSeed, testCase.clientSeed, testCase.nonce, testCase.gameId);
  for (const [i, bound] of testCase.bounds.entries()) {
    const actual = rng.below(bound);
    checkedValues += 1;
    if (actual !== testCase.values[i]) {
      failures.push(
        `case ${index} (${testCase.gameId}, nonce ${testCase.nonce}) draw ${i} ` +
          `below(${bound}): TypeScript ${actual} != Rust ${testCase.values[i]}`,
      );
    }
  }
  if (failures.length > 5) break;
}

if (failures.length > 0) {
  console.error("GOLDEN VECTOR MISMATCH -- the Rust and TypeScript RNGs have diverged.\n");
  for (const f of failures.slice(0, 6)) console.error("  " + f);
  process.exit(1);
}

console.log(
  `golden vectors OK: ${golden.cases.length} cases, ${checkedValues} draws, ` +
    `TypeScript matches Rust exactly`,
);
