/**
 * Provably-fair outcome derivation (spec Sec. 3.2).
 *
 * This file and `crates/mathsim/src/rng.rs` implement the SAME protocol and
 * must agree on every byte. `tests/golden/rng.json` is generated by the Rust
 * side and replayed here by `npm run verify:golden` -- if the two ever drift,
 * a player replaying a spin on /verify would get a different answer than the
 * server did, which destroys the only trust property that matters.
 *
 *   rawBytes = HMAC_SHA256(serverSeed, "<clientSeed>:<nonce>:<gameId>")
 *   extend   = HMAC_SHA256(serverSeed, "<clientSeed>:<nonce>:<gameId>:<counter>")
 *
 * Block 0 carries no counter suffix; block k >= 1 carries ":k".
 */

import { createHash, createHmac, randomBytes } from "node:crypto";

export const SERVER_SEED_BYTES = 32;
const BLOCK_BYTES = 32;
const TWO_POW_32 = 2 ** 32;

export function generateServerSeed(): Buffer {
  return randomBytes(SERVER_SEED_BYTES);
}

/** Published on-chain BEFORE the seed is ever used to resolve a spin. */
export function serverSeedHash(serverSeed: Buffer): string {
  return createHash("sha256").update(serverSeed).digest("hex");
}

export function hmacBlock(serverSeed: Buffer, message: string): Buffer {
  return createHmac("sha256", serverSeed).update(message, "utf8").digest();
}

/**
 * Deterministic byte stream for one (serverSeed, clientSeed, nonce, gameId).
 *
 * A spin is fully reproducible from that quadruple; if you cannot replay a
 * spin from a log line, this layer is wrong (spec Sec. 0 rule 4).
 */
export class HmacRng {
  readonly #serverSeed: Buffer;
  readonly #prefix: string;
  #block: Buffer = Buffer.alloc(BLOCK_BYTES);
  #pos = BLOCK_BYTES;
  #blockIndex = 0;
  #primed = false;

  constructor(serverSeed: Buffer, clientSeed: string, nonce: number | bigint, gameId: string) {
    this.#serverSeed = serverSeed;
    this.#prefix = `${clientSeed}:${nonce}:${gameId}`;
  }

  #refill(): void {
    let message: string;
    if (!this.#primed) {
      this.#primed = true;
      message = this.#prefix;
    } else {
      this.#blockIndex += 1;
      message = `${this.#prefix}:${this.#blockIndex}`;
    }
    this.#block = hmacBlock(this.#serverSeed, message);
    this.#pos = 0;
  }

  /** Next big-endian uint32 from the stream. */
  nextU32(): number {
    if (this.#pos + 4 > BLOCK_BYTES) this.#refill();
    const value = this.#block.readUInt32BE(this.#pos);
    this.#pos += 4;
    return value;
  }

  /** Uniform integer in [0, n) by rejection sampling. Never modulo-biased. */
  below(n: number): number {
    return uniformBelow(n, () => this.nextU32());
  }
}

/**
 * Rejection sampling shared by every caller so the acceptance rule cannot
 * drift. Values at or above the largest multiple of `n` inside the uint32
 * range are discarded; keeping them would over-represent [0, 2^32 mod n) and
 * quietly bias every reel toward its low stops.
 */
export function uniformBelow(n: number, nextU32: () => number): number {
  if (!Number.isInteger(n) || n <= 0) {
    throw new RangeError(`uniformBelow requires a positive integer, got ${n}`);
  }
  if (n === 1) return 0;
  const limit = TWO_POW_32 - (TWO_POW_32 % n);
  for (;;) {
    const x = nextU32();
    if (x < limit) return x % n;
  }
}

/** Verify a revealed seed against the hash committed on-chain. */
export function verifyServerSeed(serverSeed: Buffer, committedHash: string): boolean {
  const actual = serverSeedHash(serverSeed);
  // Constant-time-ish compare; these are public values, but habits matter.
  if (actual.length !== committedHash.length) return false;
  let diff = 0;
  for (let i = 0; i < actual.length; i++) {
    diff |= actual.charCodeAt(i) ^ committedHash.toLowerCase().charCodeAt(i);
  }
  return diff === 0;
}

/**
 * Reel stops for a spin -- the thing a player actually wants to re-derive.
 * `stripLengths` comes from the published paytable for `gameId`.
 */
export function reelStops(
  serverSeed: Buffer,
  clientSeed: string,
  nonce: number,
  gameId: string,
  stripLengths: readonly number[],
): number[] {
  const rng = new HmacRng(serverSeed, clientSeed, nonce, gameId);
  return stripLengths.map((len) => rng.below(len));
}
